name: pymol-binderized
channels:
  - schrodinger
  - samoturk
  - conda-forge
  - anaconda

dependencies:
  - python
  - pymol>=2.3
  - jupyterlab>=1.0
  - pandas
  - matplotlib
  - seaborn
  - libglu
  - glew
  - gfortran_linux-64
  - pip

  